name: Test Dissasembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -S test.c -o test.s && gcc -c test.c -o test.asm && gcc test.c -o test
    - name: test
      run: objdump -d test > test.objdump && objdump -d test.s.out > test.s.objdump && diff test.s.objdump test.objdump > test.diff
